//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAssignment2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int mid { get; set; }
        public string moviename { get; set; }
        public Nullable<System.DateTime> dateofrelease { get; set; }
    }
}
