//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Empno { get; set; }
        public string Empname { get; set; }
        public Nullable<decimal> Empsal { get; set; }
        public string Emptype { get; set; }
    }
    public class EmployeeModel
    {
        public List<Employee> Employees { get; set;}
    }
}
